stages:
- name: compilation
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/app:v1
      registry: 127.0.0.1:34687
timeout: 60
notification: {}
